// Run after `npx cap add android`. Turns the generated phone project into a TV-ready app:
// a leanback launcher entry (so it shows on the Android TV / Fire TV home screen), no touchscreen
// requirement, a TV banner and landscape orientation.
import fs from "node:fs";
import path from "node:path";

const manifestPath = path.resolve("android/app/src/main/AndroidManifest.xml");
let xml = fs.readFileSync(manifestPath, "utf8");

if (!xml.includes("android.software.leanback")) {
  xml = xml.replace(
    "<application",
    `<uses-feature android:name="android.software.leanback" android:required="false" />
    <uses-feature android:name="android.hardware.touchscreen" android:required="false" />

    <application`,
  );
}

if (!xml.includes("LEANBACK_LAUNCHER")) {
  xml = xml.replace(
    '<category android:name="android.intent.category.LAUNCHER" />',
    `<category android:name="android.intent.category.LAUNCHER" />
                <category android:name="android.intent.category.LEANBACK_LAUNCHER" />`,
  );
}

if (!xml.includes("android:banner=")) {
  xml = xml.replace("<application", '<application\n        android:banner="@drawable/tv_banner"');
}

if (!xml.includes("android:screenOrientation=")) {
  xml = xml.replace("<activity", '<activity\n            android:screenOrientation="landscape"');
}

fs.writeFileSync(manifestPath, xml);

// Use plain PNG launcher icons (generated by make_icons.py) instead of the Capacitor adaptive icon.
const anydpi = path.resolve("android/app/src/main/res/mipmap-anydpi-v26");
if (fs.existsSync(anydpi)) fs.rmSync(anydpi, { recursive: true, force: true });

for (const required of ["leanback", "LEANBACK_LAUNCHER", "android:banner", "screenOrientation"]) {
  if (!fs.readFileSync(manifestPath, "utf8").includes(required)) {
    console.error(`Manifest patch failed: missing ${required}`);
    process.exit(1);
  }
}
console.log("Android TV manifest patched.");
