alter table public.feedbacks add column if not exists approved boolean not null default false;
alter table public.feedbacks add column if not exists reviewed_at timestamptz;
update public.feedbacks set approved = true, reviewed_at = now() where approved = false;
drop policy if exists "Anyone can read public feedback columns" on public.feedbacks;
create policy "Anyone can read approved feedback" on public.feedbacks for select to anon, authenticated using (approved = true);
drop policy if exists "Authenticated users can create feedbacks" on public.feedbacks;
create policy "Users can create their own pending feedback" on public.feedbacks for insert to authenticated with check (auth.uid() = user_id and approved = false);
drop policy if exists "Users can update their own feedbacks" on public.feedbacks;
create policy "Admins can update feedback" on public.feedbacks for update to authenticated using (public.has_role(auth.uid(),'admin'::app_role)) with check (public.has_role(auth.uid(),'admin'::app_role));
create or replace view public.feedbacks_public with (security_invoker=on) as select id, display_name, content, rating, location, created_at from public.feedbacks where approved = true;
create index if not exists feedbacks_approved_created_idx on public.feedbacks (approved, created_at desc);
